### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by michaelrimbach** [rsvp/speedtest-linux#1]
Hi,

Im getting a permission denied error. You know how to handle it?

./speedtest --log
./speedtest: line 116: /dev/shm/88_speedtest_tmp.3pYeaVRNKb: Permission denied

Thanks!

**Comment by sbaghdadi** [comment]
Same here on debian wheezy.

**Comment by rsvp** [comment]
Our code curls the upstream source to file $memf, 
then does the following:

```
chmod 755 $memf
#  A file in shared memory /dev/shm needs execute permission.
```

That may be the problem.
So try resetting memf variable to a file where you have 
the ability to change permissions. 

---

Be sure the directory and file permissions are set properly.
The default name of the log file is speedtest.log 
is destined as follows in the source: 

``` sh
logdir="/home/${USER}/var/log/net"
 #    ^RENAME log directory for your personal use; for --log option.
```

Usually that path is not ready-made by the system, so 
it up to the user to handle that.

After the logdir is set, you can write to different log files, e.g.
$ speedtest --log tmp.log

Hope this resolves the issue... please write back to confirm. Thanks!

**Comment by brnhffmnn** [comment]
+1

On my system `/dev/shm` is a link to `/run/shm` -- could that be the problem?
I changed the path to `/tmp/` to make it work.

**Comment by rsvp** [comment]
@panzerfahrer Apparently:

"It's perfectly okay to use some directory in /run as long as you have the appropriate rights on it. In some modern distros, /tmp is already a virtual file system in memory or a symlink to a directory inside /run"

/tmp is perfectly fine if writing to disk is acceptable.

For Ubuntu, /dev/shm writes to shared memory, so it's just milliseconds faster :)

If /tmp works for everyone, perhaps the source should be revised. Thanks!

**Comment by rsvp** [comment]
Discussion left open for over a year... CLOSED. 

Checkout our new fasttest at https://git.io/speed
