### ISSUE TITLE
speedtest --simple doesn't work

### ISSUE THREAD

**Issue by rubo77** [rsvp/speedtest-linux#2]
```
Failed to retrieve list of speedtest.net servers

 !!  speedtest: unhandled ERR via trap, but cleanup finished. 
```

**Comment by rsvp** [comment]
@rubo77 tried it today: $ ./speedtest --simple

which gave correct readings of ping, download, and upload parameters. So most likely the dependency upstream, speedtest.net, was temporarily out of service when you tried.
