### ISSUE TITLE
USER: unbound variable  when used in a cron job

### ISSUE THREAD

**Issue by oeolartep** [rsvp/speedtest-linux#3]
I get this error when used in a cron job:
speedtest: line 92: USER: unbound variable

USER env variable isn't available when used as a cron job. I suggest using HOME variable in line 92 instead.

**Comment by rsvp** [comment]
@oeolartep Hi, made the change as you requested. Thanks very much!

Let me know if your cron job handles speedtest properly.

Some other gotchas, depending on your Linux distribution:
http://stackoverflow.com/questions/2229825/where-can-i-set-environment-variables-that-crontab-will-use
