### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by diveyez** [rsvp/speedtest-linux#6]
Timed out
root@alienware:~/sys.info# echo "$(curl -skLO https://git.io/speedtest.sh && chmod +x speedtest.sh && ./speedtest.sh)"
Cannot retrieve speedtest server list
ERROR: timed out
2018-03-15, 17:01,

**Comment by rsvp** [comment]
@diveyez hi, our script has dependencies, and occasionally 
there are *temporary transient issues* upstream which are 
beyond our control.

That error message definitely come from upstream.
The service is currently operational:

```
/tmp 0% echo "$(curl -skLO https://git.io/speedtest.sh && chmod +x speedtest.sh && ./speedtest.sh)"
2018-03-16, 08:13, 35.2, 31.40, 6.42
```

Please execute the command later, and if it still fails 
in a similar way, please pursue the matter upstream.

Thanks very much!
